# Generated by Django 2.2.12 on 2022-05-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.CharField(max_length=13)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('gender', models.TextField()),
                ('tel', models.TextField()),
                ('email', models.TextField()),
                ('birthdate', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
    ]
