# Generated by Django 2.2.12 on 2022-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0002_userlist_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
