# Generated by Django 2.2.12 on 2022-05-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0005_auto_20220530_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.CharField(max_length=13)),
                ('studentid', models.TextField()),
                ('classroom_grade', models.TextField()),
                ('classroom_room', models.TextField()),
                ('prefix', models.TextField()),
                ('name_eng', models.TextField()),
                ('surname_eng', models.TextField()),
                ('birthplace', models.TextField()),
                ('birthprovince', models.TextField()),
                ('bloodtype', models.TextField()),
                ('nationality', models.TextField()),
                ('ethenic', models.TextField()),
                ('religion', models.TextField()),
                ('language_main', models.TextField()),
                ('language_other', models.TextField()),
                ('latest_school', models.TextField()),
                ('latest_school_province', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='Info_Address',
        ),
        migrations.AddField(
            model_name='userlist',
            name='subtype',
            field=models.TextField(default='อื่นๆ'),
        ),
    ]
