# Generated by Django 2.2.12 on 2022-06-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0007_userlist_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='subtype',
        ),
    ]
