# Generated by Django 2.2.12 on 2022-06-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0009_auto_20220610_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_basic',
            name='picture',
            field=models.FileField(default='', upload_to='image/'),
        ),
    ]
