name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: |
        sudo service httpd graceful
        sudo /etc/init.d/apache2 restart 
        sudo /etc/init.d/apache2 stop
        sudo /etc/init.d/apache2 reload  
